name: oque_nao_gastei_project

services:
  redis:
    image: redis:7.2.4-alpine
    restart: always

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${NAME_DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB} -d ${NAME_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./oque_nao_gastei_django
    restart: always
    container_name: oque_nao_gastei_django
    env_file: ./oque_nao_gastei_django/.env
    environment:
      HOST_DB: db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - static_volume:/app/staticfiles
  
  frontend:
    build: 
      context: ./oque_nao_gastei_nextjs
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_ROTA_RAIZ: ${NEXT_PUBLIC_ROTA_RAIZ}
    env_file: ./oque_nao_gastei_nextjs/.env.local
    restart: always
    container_name: oque_nao_gastei_nextjs
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - backend
  
  nginx:
    image: nginx:1.27-alpine
    restart: always
    container_name: oque_nao_gastei_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/static:ro
    depends_on:
      - frontend
      - backend


volumes:
  postgres_data:
  static_volume:
