# Generated by Django 5.2.1 on 2026-07-12 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transacoes',
            name='data_transacao',
            field=models.DateField(verbose_name='Data da Transação'),
        ),
        migrations.AlterField(
            model_name='transacoes',
            name='descricao_original',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='transacoes',
            name='tipo_operacao',
            field=models.CharField(max_length=50, verbose_name='Tipo de Operação'),
        ),
        migrations.AlterField(
            model_name='transacoes',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da transação'),
        ),
    ]
