# Generated by Django 5.2.1 on 2026-07-17 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extratos', '0002_transacoes_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacoes',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='transacoes',
            name='tipo_operacao',
        ),
    ]
