# Generated by Django 5.2.1 on 2026-07-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extratos', '0003_remove_transacoes_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacoes',
            old_name='data_transacao',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='transacoes',
            old_name='descricao_original',
            new_name='descricao',
        ),
    ]
